version: "3"
services:
  nakama:
    image: heroiclabs/nakama:3.12.0
    volumes: 
      - './data/config.yml:/nakama/config.yml'
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
        ./nakama --config /nakama/config.yml
