version: "3"
services:
  metadata:
    name: api
    annotations:
      dev.okteto.com/generate-host: "domain"
  spec:
    type: ClusterIP
    ports:
      - port: 7350
        protocol: TCP
        targetPort: 7350
      - port: 7349
        protocol: TCP
        targetPort: 7349
      - port: 7348
        protocol: TCP
        targetPort: 7348
      - port: 8080
        protocol: HTTPS
        targetPort: 8080
  nakama:
    image: heroiclabs/nakama:3.12.0
    volumes: 
      - './data/config.yml:/nakama/config.yml'
    command: ['--config', '/nakama/config.yml']
    ports:
      - 8080:8080
      - 7350:7350
      - 7349:7349
      - 7348:7348
    expose:
      - 8080:8080
