version: "3"
services:
  nakama:
    image: heroiclabs/nakama:3.12.0
    volumes: 
      - './data/config.yml:/nakama/config.yml'
    command: ['--config', '/nakama/config.yml']
    endpoints:
       - path: /
         service: nakama
         port: 80
