version: "3"
services:
  nakama:
    image: heroiclabs/nakama:3.12.0
    volumes: 
      - './data/config.yml:/nakama/config.yml'
    command: ['--config', '/nakama/config.yml']
    ports:
      - 8080:8080
      - 8077:8077
      - 77:77
      - 80:80
    expose:
      - 8080:8080
