version: "3"
services:
  nakama:
    build: nakama
    image: heroiclabs/nakama:3.12.0
    volumes: 
      - './data/config.yml:/nakama/config.yml'
    command: ['nakama', '--config', '/nakama/config.yml']
