version: "3"
services:
  nakama:
    image: heroiclabs/nakama:3.12.0
    volumes: 
      - './data/config.yml:/nakama/config.yml'
    command: ['--config', '/nakama/config.yml']
    ports:
      - 8080:8080/https
      - 7350:7350/tcp
      - 7349:7349/tcp
      - 7348:7348/tcp
    expose:
      - 8080:8080
