apiVersion: apps/v1
kind: Deployment
metadata:
  name: nakama
  labels:
    app: nakama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nakama
  template:
    metadata:
      name: nakama
      labels:
        app: nakama
    spec:
      containers:
      - image: okteto.dev/nakama:latest
        name: nakama
        resources:
          limits:
            cpu: 1

---

apiVersion: v1
kind: Service
metadata:
  name: nakama
  labels:
    app: nakama
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      - port: 77
      protocol: TCP
      targetPort: 77
      - port: 7349
      protocol: TCP
      targetPort: 7349
      - port: 7350
      protocol: TCP
      targetPort: 7350
  selector:
    app: nakama
