apiVersion: apps/v1
kind: Deployment
metadata:
  name: nakama
spec:
  selector:
    matchLabels:
      app: nakama
  replicas: 1
  template:
    metadata:
      labels:
        app: nakama
    spec:
      containers:
      - name: nakama
        image: okteto.dev/nakama:latest
        ports: 
          - containerPort: 80
          - containerPort: 77
          - containerPort: 7350
          - containerPort: 7349
