apiVersion: apps/v1
kind: Deployment
metadata:
  name: nakama
spec:
  selector:
    matchLabels:
      app: enderman2003
  replicas: 1
  template:
    metadata:
      labels:
        app: firstgamescloud
    spec:
      containers:
      - name: nakama
        image: okteto.dev/nakama:latest
        ports:
        - containerPort: 8080
