apiVersion: apps/v1
kind: Deployment
metadata:
  name: nakama
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nakama
    spec:
      containers:
      - name: nakama
        image: okteto.dev/nakama:latest
        ports:
        - containerPort: 8080
        - containerPort: 8077
        - containerPort: 7350
        - containerPort: 7349
