apiVersion: v1
kind: Service
metadata:
  name: nakama
spec:
  type: LoadBalancer
  ports: 
    - name: http
      port: 80
      protocol: HTTP
    - name: tcp-7350
      port: 7350
      protocol: HTTP
    - name: tcp-7349
      port: 7349
      protocol: HTTP
    - name: tcp-77
      port: 77
      protocol: HTTP
  selector:
    app: nakama
