apiVersion: v1
kind: Service
metadata:
  name: nakama
spec:
  type: LoadBalancer
  ports: 
    - name: http
      containerPort: 80
    - name: tcp-7350
      containerPort: 7350
    - name: tcp-7349
      containerPort: 7349
    - name: tcp-77
      containerPort: 77
  selector:
    app: nakama
